name: dotnet github4women

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build the project
      run: dotnet build **/*.csproj --no-restore

    - name: Run tests
      run: dotnet test **/*.csproj --no-build --verbosity normal

    - name: Custom Script - List Files
      run: |
        echo "Listando arquivos no diretório atual:"
        ls -la

